### ISSUE TITLE
using 0.13.1 plugin does not generate .java files

### ISSUE THREAD

**Issue by teknopaul** [highsource/maven-jaxb2-plugin#105]
Its recommended not to use &lt;forceRegenerate>true&lt;/forceRegenerate>  If I remove this no .java files are created at all when running

    mvn clean compile

**Comment by highsource** [comment]
Please consider sharing important details like your `pom.xml` and `mvn clean install -X` log next time. The best would be to PR a reproducing test project under:

https://github.com/highsource/maven-jaxb2-plugin-support/issues/gh105

**Comment by vdubus** [comment]
I got the same problem, and I found out that it was because I was trying to generate the files inside another directory in which I am already generating some more java file using another maven plugin.

The problem seems to be caused by the fact that the directory is already created before `maven-jaxb2-plugin` begin its work, and so the plugin seems to consider that as the directory is more recent than the one containing the resources, it don't need to do anything.

To fix that, I would suggest to check the directory made from concatenating `generateDirectory` and `generatePackage` in place of just checking the directory pointed out by `generateDirectory`.

```xml
<plugin>
    <groupId>com.mysema.maven</groupId>
    <artifactId>apt-maven-plugin</artifactId>
    <version>${apt-maven-plugin.version}</version>
    <executions>
        <execution>
            <id>querydsl-hibernate</id>
            <goals>
                <goal>process</goal>
            </goals>
            <configuration>
                <outputDirectory>${project.build.directory}/generated-sources/java</outputDirectory>
                <processor>com.querydsl.apt.hibernate.HibernateAnnotationProcessor</processor>
            </configuration>
        </execution>
        <execution>
            <id>querydsl-ldap</id>
            <goals>
                <goal>process</goal>
            </goals>
            <configuration>
                <outputDirectory>${project.build.directory}/generated-sources/java</outputDirectory>
                <processor>org.springframework.data.ldap.repository.support.LdapAnnotationProcessor
                </processor>
            </configuration>
        </execution>
    </executions>
</plugin>
<plugin>
    <groupId>org.jvnet.jaxb2.maven2</groupId>
    <artifactId>maven-jaxb2-plugin</artifactId>
    <version>${maven-jaxb2-plugin.version}</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <schemaLanguage>WSDL</schemaLanguage>
        <generateDirectory>${project.build.directory}/generated-sources/java</generateDirectory>
        <generatePackage>org.mycompanyname.wsdl</generatePackage>
        <schemas>
            <schema>
                <fileset>
                    <directory>${basedir}/src/main/resources/wsdl</directory>
                    <includes>
                        <include>*.wsdl</include>
                    </includes>
                </fileset>
            </schema>
        </schemas>
        <forceRegenerate>true</forceRegenerate>
    </configuration>
</plugin>
```

**Comment by highsource** [comment]
> I got the same problem, and I found out that it was because I was trying to generate the files inside another directory in which I am already generating some more java file using another maven plugin.

That's actually a no-go and pretty well documented:

https://github.com/highsource/maven-jaxb2-plugin/wiki/Use-Separate-Target-Directories-for-Separate-Executions

Do not use the same directory for two generations. Use separate target directories. That's works as designed.

**Comment by highsource** [comment]
> To fix that, I would suggest to check the directory made from concatenating `generateDirectory` and `generatePackage` in place of just checking the directory pointed out by `generateDirectory`.

No, this won't solve this.

First, `generatePackage` is not obligatory and I actually generally advise against it. 

Next, there are other ways to specify generation packages.

But to wrap it all up, there is no way to know which packages will be generated - except for generating them.

From the other side, what's exactly the problem with having separate generation directories? Put results of separate generations into separate directories, what's the problem?

**Comment by vdubus** [comment]
I am generating my java files inside a `java` directory because of naming convention.
Also, I need to add these directory to the classpath so that the IDE work correctly.
That's why I was using the same output directory for all generated java file.

Is there really a need to not re-generate all files on build? As they are generated, it shouldn't be too difficult to re-create them each time (which is the most likely thing done). Is it for performance purpose?

**Comment by vdubus** [comment]
Well, putting this plugin before my other plugin does solve this problem as this `java` directory doesn't exist yet in this case.
