### ISSUE TITLE
Getting a org.xml.sax.SAXParseException "is already defined"

### ISSUE THREAD

**Issue by DenEwout** [highsource/maven-jaxb2-plugin#111]
I am getting the following Exceptions on my *.xsd files: [link to error](https://gist.github.com/DenEwout/892b60a68ceff6d56c1cf4c249eb6d8f)

It says that there is a double definition on line 47, with the first appearance being at line 10.

When looking at the file itself I don't notice any double names. The line to which the exception occurs contains: `<xs:complexType name="AfzenderAdresType">` while the "first definition" contains `<xs:complexType name="OntvangerAdresType">`. (You can find the file itself [here](https://gist.github.com/DenEwout/6b9b83bc39fa8695aeb3a8073da1864b))

The both have similar but different names and their definition is nearly identical. What is going on here? Any help as to how I can fix this?

**Comment by MichalZahir** [comment]
Were you able to solve this problem?

**Comment by javagaorui5944** [comment]
@MichalZahir  I‘m also have this problem，Were you able to solve this problem Now? Please give me some suggestions。

**Comment by highsource** [comment]
This normally happens if you have XML constructs which produce identical Java names. You normally solve it by explicitly naming classes or properties using binding files.

In case of @DenEwout I, however, don't see it. Please send a PR with a reporoducing project here:
https://github.com/highsource/maven-jaxb2-plugin-support

under g/generiek.

**Comment by buko** [comment]
BTW this happens when the same schema is being compiled twice. For example, xsd:imports and schemas and episodes defined in the pom.xml. It's very confusing. I spent quite a while figuring out how to do modular schema builds with the plugin that don't produce errors like that. Work is documented in https://github.com/bubblegumproject/scrum4j-model

**Comment by highsource** [comment]
No reply from @DenEwout - closing.

**Comment by hkhald01** [comment]
> BTW this happens when the same schema is being compiled twice. For example, xsd:imports and schemas and episodes defined in the pom.xml. It's very confusing. I spent quite a while figuring out how to do modular schema builds with the plugin that don't produce errors like that. Work is documented in https://github.com/bubblegumproject/scrum4j-model

I had the same issue in Netbeans 8, maven project  (I created a foloder like a temp folder with the xsd file then I copied it to the src/main/resources/ ) it was alaways giving  me the xsd  is already defined, I removed the temp folder and it worked 
thanks

**Comment by maffe** [comment]
I got the same exception with these two XSD files:
- http://xmlapi.nic-direct.de/ch02.html#cnt_create
- http://xmlapi.nic-direct.de/ch02.html#cnt_activate

It worked after I added a unique targetNamespace to each of the XSD files. This doesn’t appear to change the generated Java files in any way.
