### ISSUE TITLE
[ERROR] Could not retrieve the last modification timestamp for the URI [https://somehost/some/service?wsdl] from the HTTP URL connection. The [Last-Modified] header was probably not set correctly.

### ISSUE THREAD

**Issue by danielpacak** [highsource/maven-jaxb2-plugin#67]
I have a WebService/WSDL provided by some 3rd party company. However they do not return the `Last-Modified` header. Therefore my attempt to generate java code fails. Is there any reason to do such strict validation? Technically it makes this plugin useless in my case. I had a flick through code and plugin's config params and cannot find any way to disable validation.

**Comment by highsource** [comment]
I don't think that it's why code generation fails. The error you see is just a console message, see [this code](https://github.com/highsource/maven-jaxb2-plugin/blob/f027e3453987195049f229c05b4f97f187460170/plugin-core/src/main/java/org/jvnet/jaxb2/maven2/net/AbstractHTTPURILastModifiedResolver.java#L41-L45).

This should not fail the code generation.

Post `mvn clean install -e -X` log, maybe there's something else.

As a workaround make a local copy and use a catalog to rewrite the absolute URL. I consider compiling resources from the internet a bad practice.

**Comment by danielpacak** [comment]
My bet. Thanks for a prompt reply. Indeed the problem is with the WSDL itself and I have to tweak a local copy to make it JAXB friendly anyway. I was somehow mislead by the ERROR message but the plugin works perfectly fine!

**Comment by ryanstull** [comment]
I had the same issue and you solution worked for me @highsource, thanks!

**Comment by sadiasher** [comment]
> My bet. Thanks for a prompt reply. Indeed the problem is with the WSDL itself and I have to tweak a local copy to make it JAXB friendly anyway. I was somehow misled by the ERROR message but the plugin works perfectly fine!

how you make JAXB friendly copy, I am facing the same issue and unable to resolve it.

**Comment by Marina879** [comment]
> > My bet. Thanks for a prompt reply. Indeed the problem is with the WSDL itself and I have to tweak a local copy to make it JAXB friendly anyway. I was somehow misled by the ERROR message but the plugin works perfectly fine!
> 
> how you make JAXB friendly copy, I am facing the same issue and unable to resolve it.

I have the same problem. Did you solve it?

**Comment by highsource** [comment]
@Marina879 @sadiasher Not sure what your problem is. Just make a local copy of the schema/WSDL you try to compile and compile it. You can also use catalogs to rewrite absolute URLs into local locations:
https://github.com/highsource/maven-jaxb2-plugin/wiki/Using-Catalogs

If your schema/WSDL is invalid (which is not quite rare), you might need to fix it or patch it prior to compilation. This is, however not in scope of the `maven-jaxb2-plugin`, you'll need to construct something on you own here. This is how I do it in one project:

https://github.com/highsource/ogc-schemas/tree/master/schemas

I use `maven-patch-plugin` to patch schemas before compilation. My changes are saved in a patch file which I apply to schemas I download.

**Comment by jcatino** [comment]
> > > My bet. Thanks for a prompt reply. Indeed the problem is with the WSDL itself and I have to tweak a local copy to make it JAXB friendly anyway. I was somehow misled by the ERROR message but the plugin works perfectly fine!
> > 
> > 
> > how you make JAXB friendly copy, I am facing the same issue and unable to resolve it.
> 
> I have the same problem. Did you solve it?

@Marina879 I solved the problem using the 0.11.0 version of the plugin : 


			<plugin>
			    <groupId>org.jvnet.jaxb2.maven2</groupId>
			    <artifactId>maven-jaxb2-plugin</artifactId>
			    <version>0.11.0</version>
			    <executions>
			        <execution>
			            <goals>
			                <goal>generate</goal>
			            </goals>
			        </execution>
			    </executions>
			    <configuration>
			        <schemaLanguage>WSDL</schemaLanguage>
			        <generatePackage>AccPaymentGateway.wsdl</generatePackage>
			        <schemas>
			            <schema>
			            	<url>(your schema URL here)</url>
			            </schema>
			        </schemas>
			    </configuration>
			</plugin>

**Comment by Snesi** [comment]
Thank you @jcatino ! That solved the problem for me too.

**Comment by qq253498229** [comment]
@jcatino That solved the problem for me too.
On 0.14.0 version, I found it was success but show error log .

**Comment by CorrioneroFederico** [comment]
I tried with the 0.11.0 version but when i compile the console show me that i'm using te version 0.14.0.
I can't make a local copy either, because it's out of my permission
If anyone have another solution is welcome.

--- maven-jaxb2-plugin:0.14.0:generate (default) @ demo ---
The URI [http://url:port/service?wsdl] seems to represent an absolute HTTP or HTTPS URL. Getting the last modification timestamp is only possible if the URL is accessible and if the server returns the [Last-Modified] header correctly. This method is not reliable and is likely to fail. In this case the last modification timestamp will be assumed to be unknown.

Could not retrieve the last modification timestamp for the URI [http://url:port/service?wsdl] from the HTTP URL connection. The [Last-Modified] header was probably not set correctly.

Last modification of the URI [http://url:port/service?wsdl] is not known.

Sources are not up-to-date, XJC will be executed.

Error while parsing schema(s).Location [ http://url:port/service?wsdl{1,42}].

**Comment by anupdarvatkar** [comment]
Getting the same error as @CorrioneroFederico .

[WARNING] The URI [https://****.oraclecloud.com/GC3Services/TransmissionService/call?wsdl] seems to represent an absolute HTTP or HTTPS URL. Getting the last modification timestamp is only possible if the URL is accessible and if the server returns the [Last-Modified] header correctly. This method is not reliable and is likely to fail. In this case the last modification timestamp will be assumed to be unknown.
[ERROR] Could not retrieve the last modification timestamp for the URI [https://****.oraclecloud.com/GC3Services/TransmissionService/call?wsdl] from the HTTP URL connection. The [Last-Modified] header was probably not set correctly.
;
;
;
[INFO] Parsing input schema(s)...
[DEBUG] Resolving publicId [null], systemId [https://****.ocs.oraclecloud.com:443/GC3Services/TransmissionService/call?xsd=15].
resolveSystem(https://****.ocs.oraclecloud.com:443/GC3Services/TransmissionService/call?xsd=15)
[DEBUG] Parent resolver has resolved publicId [null], systemId [https://****.ocs.oraclecloud.com:443/GC3Services/TransmissionService/call?xsd=15] to [null].

The build finally fails will Null Pointer.
