### ISSUE TITLE
Resolve JAXB plugins via pluginRepositories instead of repositories.

### ISSUE THREAD

**Issue by danilevdokimov** [highsource/maven-jaxb2-plugin#71]
Why your plugin resolve artifacts for configuration in plugins tag from project repositories?
Plugin must resolve artifact from plugin repositories.

**Comment by highsource** [comment]
I don't see this as a bug. Below is my argumentation.

Quoting [Maven - POM Reference - Plugin Repositories](https://maven.apache.org/pom.html#Plugin_Repositories):

> # Plugin Repositories
> Repositories are home to two major types of artifacts. The first are artifacts that are used as dependencies of other artifacts. These are the majority of plugins that reside within central. The other type of artifact is plugins. Maven plugins are themselves a special type of artifact. Because of this, plugin repositories may be separated from other repositories **(although, I have yet to hear a convincing argument for doing so)**. In any case, the structure of the `pluginRepositories` element block is similar to the `repositories` element. The `pluginRepository` elements each specify a remote location of where Maven can find new plugins.

My emphasis.

So the current situation is:

* `pluginRepositories` should be used for Maven plugins. JAXB plugins could also be considered this "special type of artifact" and could also be resolved via `pluginRepositories`.
* Maven authors don't know a "convincing argument" for this separation. Me neither.
* There is no formal requirement from Maven for JAXB plugins to be considered "special type of artifact".
* JAXB plugins are resolved from normal `repositories`, not from `pluginRepositories`.
* Changing this to `pluginRepositories` may (and likely will) break existing builds.
* Fixing builds may be quite ugly. Either people will have to configure their `repositories` as `pluginRepositories` or redeploy JAXB plugins to their `pluginRepositories`.

Do you happen to have a "convincing argument" for why JAXB plugins should be resolved via `pluginRepositories`? What would be a technical reasons for doing that?

Otherwise inclined to close this as `wontfix`. Fixing this as you propose will damage the status quo, for reasons which are currently not clear to me.
