### ISSUE TITLE
Plugin fail for attribute default values

### ISSUE THREAD

**Issue by tpd-opitz** [highsource/maven-jaxb2-plugin#88]
In my projects I generate Java classes from XSD files.

so far I used org.codehouse.mojo:jaxb2-mave-plugin:1.5

Since I need to introduce Java8 property bindings I changed to org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1.

I ran into the problem that this plugin does not respect the default value definition for an attribute.

The sample project [https://github.com/tpd-opitz/maven-jaxb22-plugin-attribute-default-demo](https://github.com/tpd-opitz/maven-jaxb22-plugin-attribute-default-demo) demonstrates the wrong behavior. 
the JUnitTest provided used to pass with org.codehouse.mojo:jaxb2-mave-plugin:1.5 but it fails with org.jvnet.jaxb2.maven2(2):maven-jaxb2-plugin:0.13.1.

[build.log.txt.zip](https://github.com/highsource/maven-jaxb2-plugin/files/161738/build.log.txt.zip)

TPD

**Comment by highsource** [comment]
Your problem comes from the `-Xgenerate-fx-properties` plugin.

If I disable this plugin in your build, I'm getting the following getter:

```
    public int getTest() {
        if (test == null) {
            return  42;
        } else {
            return test;
        }
    }
```

If I enable this plugin, I'm getting:

```
    public ObjectProperty<Integer> testProperty() {
        if (this.testProxy == null) {
            this.testProxy = new SimpleObjectProperty<Integer>();
            this.testProxy.set(this.test);
            this.testProxy.addListener((observable, oldValue, newValue) -> {this.test = (Integer)newValue; });
        }
        return this.testProxy;
    }

    public Integer getTest() {
        if (this.test == null) {
            return this.test;
        } else {
            return testProperty().get();
        }
    }
```

No sign of the default value `42`.

Please report this to the authors of the `-Xgenerate-fx-properties` plugin. This plugin clearly does not consider default values when generating code.

You could have found this out on your own if you'd try to reduce your build to the bare minimum. Your example has five plugins, any of these could have been introducing this problem, and one was it.

Closing as invalid.

**Comment by tpd-opitz** [comment]
Thanks for looking at my problem.

I opened an issue at the [jaxbfx](https://github.com/tpd-opitz/jaxbfx) project

bye
TPD
